// <auto-generated />
using DataAccess.Context;
using DataAccess.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DAL.Migrations;

[DbContext(typeof(EntityContext<Item>))]
partial class DbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.10");

        modelBuilder.Entity("DataAccess.Entities.Item", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("Code")
                    .HasColumnType("int");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(255)");

                b.HasKey("Id");

                b.ToTable("Items");
            });
    }
}
